# Generated by Django 2.1.7 on 2019-03-21 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ferias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_empresa', models.IntegerField(blank=True)),
                ('id_funcionario', models.IntegerField(blank=True)),
                ('id_vinculo', models.IntegerField(blank=True)),
                ('id_per_aquisitivo', models.IntegerField(blank=True)),
                ('nome', models.CharField(max_length=80)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='ferias',
            unique_together={('id_empresa', 'id_funcionario', 'id_vinculo', 'id_per_aquisitivo')},
        ),
    ]
