# Generated by Django 2.1.7 on 2019-03-21 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ferias',
            name='avisoprazo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='datalimite',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_abono',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_com_deducao_faltas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_direito',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_gozados',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_saldo',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='dias_saldo_v2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='faltas_nao_justificadas',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='fim_per_aquisitivo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='fim_per_concessivo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='inicio_per_aquisitivo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='inicio_per_concessivo',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='ferias',
            name='status',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='nome',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
