# Generated by Django 2.1.7 on 2019-03-21 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0002_auto_20190321_1103'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='id_empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=None, to='empresa.Empresa'),
        ),
    ]
