# Generated by Django 2.1.7 on 2019-03-21 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0003_auto_20190321_1305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='id_empresa',
            field=models.ForeignKey(blank=True, default=0, on_delete=None, to='empresa.Empresa'),
            preserve_default=False,
        ),
    ]
