# Generated by Django 2.1.7 on 2019-03-21 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ferias', '0006_remove_ferias_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferias',
            name='dias_com_deducao_faltas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='dias_direito',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='dias_saldo',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='dias_saldo_v2',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='ferias',
            name='faltas_nao_justificadas',
            field=models.DecimalField(decimal_places=2, max_digits=15, null=True),
        ),
    ]
