# Generated by Django 2.1.7 on 2019-05-03 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Musica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=80)),
                ('musica_file', models.FileField(blank=True, null=True, upload_to='musicas/', verbose_name='')),
                ('genero', models.ForeignKey(on_delete=None, to='musicas.Genero')),
            ],
        ),
    ]
