# Generated by Django 2.1.7 on 2019-03-14 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_auto_20190314_1545'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dependente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomeDependente', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='dependentes',
            field=models.ManyToManyField(blank=True, null=True, to='clientes.Dependente'),
        ),
    ]
