# Generated by Django 2.1.7 on 2019-03-20 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nro_inscricao', models.CharField(max_length=14)),
                ('razao_social', models.CharField(max_length=80)),

            ],
        ),
    ]
