# Generated by Django 2.1.7 on 2019-03-20 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='empresa',
            name='cod_empresa',
            field=models.CharField(default=0, max_length=80),
            preserve_default=False,
        ),
    ]
