# Generated by Django 2.1.7 on 2019-03-20 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_empresa_cod_empresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='cod_empresa',
            field=models.IntegerField(blank=True, max_length=100),
        ),
    ]
