# Generated by Django 2.1.7 on 2019-04-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=80, null=True)),
                ('categoria', models.CharField(max_length=80, null=True)),
                ('sinopse', models.CharField(max_length=80000, null=True)),
                ('ano', models.IntegerField(blank=True, null=True)),
                ('videofile', models.FileField(null=True, upload_to='filmes/', verbose_name='')),
            ],
        ),
    ]
