# Generated by Django 2.1.7 on 2019-04-30 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='videofile',
            field=models.FileField(blank=True, null=True, upload_to='filmes/', verbose_name=''),
        ),
    ]
